name: Package-Install

on: workflow_call

jobs:
  node-install:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: Install Node.js dependencies
        run: npm ci
